### ISSUE TITLE
The model compiler of OpenVINO does not support TensorFlow 2.x.

### ISSUE THREAD

**Issue by KellyZhang2020** [Adlik/Adlik#138]
When I compile the model to OpenVINO type, the error is as follows:
`AttributeError: module 'tensorflow' has no attribute 'NodeDef'`

**Comment by amadeus-zte** [comment]
Do you have any evidence that OpenVINO could not suppport TF2.x model? @KellyZhang2020

**Comment by KellyZhang2020** [comment]
The issue of the OpenVINO does not support TensorFlow 2.x in the openvino-toolkit.

> https://software.intel.com/en-us/forums/intel-distribution-of-openvino-toolkit/topic/827537

**Comment by amadeus-zte** [comment]
@KellyZhang2020  
How about openvino 2020? Could it support tf2.x model ?

**Comment by amadeus-zte** [comment]
@wangzhenyu32  Could this issue be closed?  I think you test openvino2020 with tf2.x model. Right?

**Comment by wangzhenyu32** [comment]
Yes, OpenVINO2020 has already supported TensorFlow 2.x in the openvino-toolkit

**Comment by wangzhenyu32** [comment]
> @wangzhenyu32 Could this issue be closed? I think you test openvino2020 with tf2.x model. Right?

Yes, OpenVINO2020 has already supported TensorFlow 2.x in the openvino-toolkit
