### ISSUE TITLE
TfLite run-time should support ARM CPU

### ISSUE THREAD

**Issue by amadeus-zte** [Adlik/Adlik#147]
Considering two scenario:
- Use QEMU ARM64 emulator. 
1. Provide cross-compile tool-chain for ARM-64.
2. Compile ServingLite framework and TfLite runtime, and run inference test with Tflite Model ( Resnet50). 
3. Considering several optimizing methods for TfLite Model, the specification of performance tests should be clear, and cover as many scenes as possible.

- Support real device such as Raspberry Pi or Nvidia Jetson Nano. 
1. Provide specific cross-compile tool-chain.
2. Compile ServingLite framework and TfLite runtime, and run TfLite Model in device successfully.

**Comment by austinzh** [comment]
I will take a look at it.
Assign to me please.
