### ISSUE TITLE
Openvino model compiler, "enable_nhwc_to_nchw" keyword should be set when user provide "input_format" keyword

### ISSUE THREAD

**Issue by NaNAGISaSA** [Adlik/Adlik#368]
When compile openvino model, I give `input_format` as `channel_last`, but only when I give another keyword `enable_nhwc_to_nchw` as `True`, the model can be compiled successfully.

As the schema says: 
https://github.com/Adlik/Adlik/blob/7c58defd8e25756583e698ef5e30cd83cc8f0110/model_compiler/config_schema.json#L97-L100

Compiler code can set `enable_nhwc_to_nchw` to correct value if the user has given `input_format` keyword, so the user should compile the model successfully when he only gives `input_format`(now will get failure).

**Comment by wangzhenyu32** [comment]
When set enable_nhwc_to_nchw=true default and user give a channel_last model, but the result will give a channel_first model, while user don't know the user's model  channels has been changed.
