### ISSUE TITLE
Add Some Tags For This Project

### ISSUE THREAD

**Issue by NaNAGISaSA** [Adlik/Adlik#401]
For a better search result in github, we can add some tags for adlik project, for example:
`deep learning`, 
`inference`, 
`performance`,
`tensorflow serving`,
`openvino`,
`tensorrt`,
`compiler`,
`http`,
`grpc`,
`inference engine`,
etc.

**Comment by NaNAGISaSA** [comment]
@shiyingjin @amadeus-zte

**Comment by amadeus-zte** [comment]
Tags added. Close this issue.
