### ISSUE TITLE
what is structural compression 

### ISSUE THREAD

**Issue by hnuhchen** [Adlik/Adlik#417]
Hello, in README.md, there is
```
Model Compiler
Model compiler supports several optimizing technologies like pruning, quantization and structural compression, which can be easily used for models developed with TensorFlow, Keras, PyTorch, etc.
```
But I cannot find anything about structure compression. So i want to know what structure compression is? Can you tell me anything about that? Thank you

**Comment by amadeus-zte** [comment]
The structure compression with my understanding is some technique such as matrix decomposition, or depthwise convolution layer, and others. 
In Adlik, there was an idea of adopting such kind of technique. However we did not commit further research yet.

**Comment by hnuhchen** [comment]
@amadeus-zte ,thank you. Do you have the roadmap of adding structure compresion  to adlik?

**Comment by amadeus-zte** [comment]
@hnuhchen  Not yet. Because this feature is model-specific, and Adlik would not take it into consideration unless discussing in TSC meeting. You could check meeting info in https://adlik.ai/ .

**Comment by hnuhchen** [comment]
@amadeus-zte, thank you
