### ISSUE TITLE
Update CI Image To Ubuntu 20.04

### ISSUE THREAD

**Issue by NaNAGISaSA** [Adlik/Adlik#594]
According to this [link](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/), ubuntu 18.04 image will be deprecated at 12-1-22, so we should update our ci image before the day.

**Comment by shiyingjin** [comment]
Closed by #621.
